services:
  appointment-management:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb+srv://lasannavodya:DelLCS5EiIBT3jFu@course.uf2pi.mongodb.net/HealthCare?retryWrites=true&w=majority&appName=Course
      APPOINTMENT_MANAGEMENT_PORT: 8080
      PATIENT_SERVICE_BASE_URL: http://patient-management:8081
      DOCTOR_SERVICE_BASE_URL: http://patient-management:8081
      NOTIFICATION_SERVICE_URL: http://notification-management:8084
      JWT_SECRET: ${JWT_SECRET:-dev-secret-change-me}
